import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/header/Header";
import Footer from "./component/layout/footer/Footer";
import { AppProvider } from "./context/Appcontext";

export const metadata: Metadata = {
  title: "DoctorRecomend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppProvider>
        <Header/>
        {children}
        <Footer/>
        </AppProvider>
        
      </body>
    </html>
  );
}
